apiVersion: v1
kind: Pod
metadata:
  name: adservice-manual
  labels:
    name: adservice-manual
spec:
  containers:
  - name: adservice-manual
    image: java-otel-manual:v1
    imagePullPolicy: Never
    env:
    - name: HONEYCOMB_API_KEY
      value: ${HONEYCOMB_API_KEY}
    - name: AD_SERVICE_PORT
      value: "8080"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
